CREATE TABLE ACCOUNT
(
    ACCOUNT_NUMBER VARCHAR(255) NOT NULL,
    BANK           TINYINT      NOT NULL, -- 0 = 신한은행, 1 = 농협, 2 = KB은행, 3 = 우리은행, 4 = 카카오뱅크, 5 = 토스뱅크
    BALANCE        BIGINT       NOT NULL,
    PERSON_ID      BIGINT       NOT NULL    UNIQUE,
    CREATION_DATE_TIME  DATETIME  NOT NULL, -- 형식: YYYY-mm-DD HH:MM:SS
    PRIMARY KEY (ACCOUNT_NUMBER, BANK),
    CONSTRAINT FK_PERSON_IN_ACCOUNT
        FOREIGN KEY (PERSON_ID) REFERENCES PERSON
);
