INSERT INTO ITEM
    (name, price, quantity, kind, author, actor, director, artist, painter, description)
VALUES
    ('The Shawshank Redemption', 9.99, 5, 1, null, 'Tim Robbins', 'Frank Darabont', null, null, 'A classic movie about hope and friendship'),
    ('The Godfather', 14.99, 3, 1, null, 'Marlon Brando', 'Francis Ford Coppola', null, null, 'A classic crime drama about a powerful mafia family'),
    ('The Dark Knight', 9.49, 4, 1, null, 'Christian Bale', 'Christopher Nolan', null, null, 'A superhero movie about the iconic DC Comics character Batman'),
    ('Pulp Fiction', 12.99, 4, 1, null, 'John Travolta', 'Quentin Tarantino', null, null, 'A classic crime movie with a nonlinear narrative'),
    ('Fight Club', 10.99, 3, 1, null, 'Brad Pitt', 'David Fincher', null, null, 'A movie about a secret underground fight club'),
    ('Inception', 5.6, 5, 1, null, 'Leonardo DiCaprio', 'Christopher Nolan', null, null, 'A movie about a team of thieves who enter peoples dreams to steal their secrets'),
    ('The Silence of the Lambs', 9.99, 2, 1, null, 'Jodie Foster', 'Jonathan Demme', null, null, 'A classic thriller about a young FBI agent seeking the help of a cannibalistic serial'),
    ('The Matrix', 9.29, 3, 1, null, 'Keanu Reeves', 'The Wachowski Brothers', null, null, 'A science fiction movie about a hacker who discovers the world is a simulated reality'),
    ('Goodfellas', 1.99, 4, 1, null, 'Robert De Niro', 'Martin Scorsese', null, null, 'A classic crime movie about the rise and fall of a group of mobsters'),
    ('Forrest Gump', 3.99, 2, 1, null, 'Tom Hanks', 'Robert Zemeckis', null, null, 'A classic movie about an intellectually disabled man who becomes successful'),
    ('The Prestige', 4.99, 3, 1, null, 'Christian Bale', 'Christopher Nolan', null, null, 'A movie about two rival magicians'),
    ('Django Unchained', 5.99, 4, 1, null, 'Jamie Foxx', 'Quentin Tarantino', null, null, 'A western movie about a freed slave who becomes a bounty hunter'),
    ('Interstellar', 44.99, 5, 1, null, 'Matthew McConaughey', 'Christopher Nolan', null, null, 'A science fiction movie about a group of astronauts who travel through a wormhole'),
    ('Mad Max: Fury Road', 9.99, 4, 1, null, 'Tom Hardy', 'George Miller', null, null, 'A post-apocalyptic movie about a group of rebels who fight against a tyrannical ruler'),
    ('Gladiator', 9.99, 3, 1, null, 'Russell Crowe', 'Ridley Scott', null, null, 'A movie about a Roman general who becomes a gladiator after being betrayed'),
    ('Dark Side of the Moon', 12.99, 5, 2, null, null, null, 'Pink Floyd', null, 'A classic rock album with iconic songs like "Money" and "Time"'),
    ('Thriller', 9.99, 3, 2, null, null, null, 'Michael Jackson', null, 'An iconic pop album with hits like "Beat It" and "Thriller"'),
    ('The Marshall Mathers LP', 14.99, 4, 2, null, null, null, 'Eminem', null, 'A classic rap album with hits like "The Real Slim Shady" and "The Way I Am"'),
    ('Back in Black', 11.99, 2, 2, null, null, null, 'AC/DC', null, 'A classic rock album with hits like "Hells Bells" and "You Shook Me All Night Long"'),
    ('Appetite for Destruction', 19.99, 5, 2, null, null, null, 'Guns N', null, 'A classic rock album with hits like "Sweet Child o'' Mine" and "Paradise City"'),
    ('The Wall', 16.99, 4, 2, null, null, null, 'Pink Floyd', null, 'A classic rock album with hits like "Another Brick in the Wall" and "Comfortably Numb"'),
    ('Born in the U.S.A.', 14.99, 3, 2, null, null, null, 'Bruce Springsteen', null, 'A classic rock album with hits like "Dancing in the Dark" and "Born in the U.S.A."'),
    ('The Bodyguard Soundtrack', 11.99, 5, 2, null, null, null, 'Various Artists', null, 'The soundtrack to the classic movie featuring hits like "I Will Always Love You" by Whitney Houston'),
    ('Nevermind', 14.99, 3, 2, null, null, null, 'Nirvana', null, 'A classic rock album with hits like "Smells Like Teen Spirit" and "Come as You Are"'),
    ('Hybrid Theory', 9.99, 4, 2, null, null, null, 'Linkin Park', null, 'A classic rock album with hits like "One Step Closer" and "Crawling"'),
    ('The Black Parade', 14.99, 2, 2, null, null, null, 'My Chemical Romance', null, 'A classic rock album with hits like "Welcome to the Black Parade" and "I Don''t Love You"'),
    ('The White Stripes', 9.99, 3, 2, null, null, null, 'The White Stripes', null, 'A classic rock album with hits like "Seven Nation Army" and "Icky Thump"'),
    ('Their Greatest Hits', 19.99, 5, 2, null, null, null,'Eagles', null, 'A compilation of classic rock hits by the Eagles, including "Hotel California" and "Take It to the Limit"'),
    ('The Bends', 14.99, 4, 2, null, null, null, 'Radiohead', null, 'A classic rock album with hits like "Fake Plastic Trees" and "High and Dry"'),
    ('Kid A', 9.99, 3, 2, null, null, null, 'Radiohead', null, 'A classic rock album with hits like "Everything in Its Right Place" and "The National Anthem"'),
    ('The Miseducation', 19.99, 2, 2, null, null, null, 'Lauryn Hill', null, 'A classic rap/R&B album with hits like "Doo Wop (That Thing)" and "Ex-Factor"'),
    ('The Great Gatsby', 9.99, 5, 3, 'F. Scott Fitzgerald', null, null, null, null, 'A classic novel about love, greed, and excess in the Roaring Twenties'),
    ('To Kill a Mockingbird', 14.99, 3, 3, 'Harper Lee', null, null, null, null, 'A classic novel about racial injustice and growing up in the South'),
    ('Pride and Prejudice', 11.99, 4, 3, 'Jane Austen', null, null, null, null, 'A classic novel about love, marriage, and societal expectations in early 19th century England'),
    ('The Catcher in the Rye', 9.99, 2, 3, 'J.D. Salinger', null, null, null, null, 'A classic novel about the struggles of adolescence and identity'),
    ('The Lord of the Rings', 19.99, 5, 3, 'J.R.R. Tolkien', null, null, null, null, 'A classic fantasy novel about a group of heroes on a quest to destroy a powerful artifact'),
    ('The Grapes of Wrath', 14.99, 4, 3, 'John Steinbeck', null, null, null, null, 'A classic novel about the Great Depression and the struggles of a poor, migrant family in California'),
    ('Wuthering Heights', 9.99, 3, 3, 'Emily Brontë', null, null, null, null, 'A classic novel about love, obsession, and betrayal set on the bleak moors of England'),
    ('The Great Expectations', 19.99, 2, 3, 'Charles Dickens', null, null, null, null, 'A classic novel about a young man''s journey from poverty to wealth and the lessons he learns along the way'),
    ('The Starry Night', 199.99, 5, 4, null, null, null, null, 'Vincent van Gogh', 'A famous painting of a night sky with swirling stars and a cypress tree'),
    ('The Persistence of Memory', 149.99, 3, 4, null, null, null, null, 'Salvador Dalí', 'A surrealist painting featuring melting clocks'),
    ('The Last Supper', 119.99, 4, 4, null, null, null, null, 'Leonardo da Vinci', 'A painting of Jesus and his apostles during the Last Supper'),
    ('The Mona Lisa', 99.99, 2, 4, null, null, null, null, 'Leonardo da Vinci', 'A famous painting of a woman with an enigmatic smile'),
    ('The Scream', 199.99, 5, 4, null, null, null, null, 'Edvard Munch', 'A painting of a figure with an anguished expression against a backdrop of a turbulent sea and sky'),
    ('The Madonna and Child', 149.99, 4, 4, null, null, null, null, 'Sandro Botticelli', 'A painting of the Virgin Mary holding the infant Jesus'),
    ('The Birth of Venus', 99.99, 3, 4, null, null, null, null, 'Sandro Botticelli', 'A painting of the goddess Venus being born from a seashell'),
    ('The Old Guitarist', 199.99, 2, 4, null, null, null, null, 'Pablo Picasso', 'A painting of an old, haggard man playing a guitar'),
    ('Girl with a Pearl Earring', 149.99, 3, 4, null, null, null, null, 'Johannes Vermeer', 'A painting of a young woman with a pearl earring'),
    ('The Kiss', 119.99, 4, 4, null, null, null, null, 'Gustav Klimt', 'A painting of a couple embracing'),
    ('The Thinker', 99.99, 2, 4, null, null, null, null, 'Auguste Rodin', 'A sculpture of a man deep in thought'),
    ('The Love Letter', 199.99, 5, 4, null, null, null, null, 'Jan Vermeer', 'A painting of a woman reading a letter'),
    ('The Catchers in the Rye', 99.99, 3, 4, null, null, null, null, 'J.D. Salinger', 'A classic novel about the struggles of adolescence and identity'),
    ('Table', 199.99, 5, 0, null, null, null, null, null, 'A wooden table with four legs'),
    ('Chair', 149.99, 3, 0, null, null, null, null, null, 'A wooden chair with four legs and a backrest'),
    ('Sofa', 119.99, 4, 0, null, null, null, null, null, 'A couch with a soft, padded surface and armrests'),
    ('Computer', 149.99, 4, 0, null, null, null, null, null, 'An electronic device for storing and processing data'),
    ('Television', 199.99, 5, 0, null, null, null, null, null, 'A device for displaying television programs'),
    ('Lamp', 99.99, 2, 0, null, null, null, null, null, 'A light fixture with a base and a shade'),
    ('Fridge', 119.99, 4, 0, null, null, null, null, null, 'A device for storing food and drinks at a cool temperature'),
    ('Clock', 149.99, 3, 0, null, null, null, null, null, 'A device for measuring and displaying time'),
    ('Microwave', 99.99, 2, 0, null, null, null, null, null, 'A device for cooking or heating food using microwaves'),
    ('Blender', 149.99, 4, 0, null, null, null, null, null, 'A device for mixing and blending foods or drinks'),
    ('Food Processor', 99.99, 3, 0, null, null, null, null, null, 'A device for chopping, grinding, or pureeing food'),
    ('Toaster', 199.99, 5, 0, null, null, null, null, null, 'A device for toasting bread');








